apiVersion: b2.m.crossplane.io/v1alpha1
kind: BucketNotificationRules
metadata:
  name: example-crossplane-bucket
  namespace: crossplane-system
spec:
  forProvider:
    bucketRef:
      name: example-crossplane-bucket
    notificationRules:
      - name: rule-1
        eventTypes:
          - b2:ObjectCreated:*
          - b2:ObjectDeleted:*
        targetConfiguration:
          - targetType: webhook
            url: https://example.com/webhook
  providerConfigRef:
    kind: ProviderConfig
    name: default
