// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this ApplicationKey.
func (mg *ApplicationKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var mrsp reference.MultiResolutionResponse
	var err error

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.ForProvider.BucketIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.ForProvider.BucketIdsRefs,
		Selector:      mg.Spec.ForProvider.BucketIdsSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BucketIds")
	}
	mg.Spec.ForProvider.BucketIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.ForProvider.BucketIdsRefs = mrsp.ResolvedReferences

	mrsp, err = r.ResolveMultiple(ctx, reference.MultiResolutionRequest{
		CurrentValues: reference.FromPtrValues(mg.Spec.InitProvider.BucketIds),
		Extract:       reference.ExternalName(),
		Namespace:     mg.GetNamespace(),
		References:    mg.Spec.InitProvider.BucketIdsRefs,
		Selector:      mg.Spec.InitProvider.BucketIdsSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BucketIds")
	}
	mg.Spec.InitProvider.BucketIds = reference.ToPtrValues(mrsp.ResolvedValues)
	mg.Spec.InitProvider.BucketIdsRefs = mrsp.ResolvedReferences

	return nil
}

// ResolveReferences of this BucketFileVersion.
func (mg *BucketFileVersion) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BucketID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BucketIDRef,
		Selector:     mg.Spec.ForProvider.BucketIDSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BucketID")
	}
	mg.Spec.ForProvider.BucketID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BucketIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BucketID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BucketIDRef,
		Selector:     mg.Spec.InitProvider.BucketIDSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BucketID")
	}
	mg.Spec.InitProvider.BucketID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BucketIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BucketNotificationRules.
func (mg *BucketNotificationRules) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BucketID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BucketIDRef,
		Selector:     mg.Spec.ForProvider.BucketIDSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BucketID")
	}
	mg.Spec.ForProvider.BucketID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BucketIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BucketID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BucketIDRef,
		Selector:     mg.Spec.InitProvider.BucketIDSelector,
		To: reference.To{
			List:    &BucketList{},
			Managed: &Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BucketID")
	}
	mg.Spec.InitProvider.BucketID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BucketIDRef = rsp.ResolvedReference

	return nil
}
